export const INTERESTS = [
  // Technology & Digital
  'Coding',
  'Web Development',
  'Mobile Apps',
  'AI & Machine Learning',
  'Cybersecurity',
  'Data Science',
  'Gaming',
  'Game Development',
  'VR/AR',
  'Blockchain',
  'Robotics',
  // Arts & Creative
  'Art',
  'Drawing',
  'Painting',
  'Digital Art',
  'Photography',
  'Videography',
  'Graphic Design',
  'UI/UX Design',
  'Animation',
  'Film Making',
  'Music',
  'Singing',
  'Playing Instruments',
  'Music Production',
  'DJing',
  'Dancing',
  'Theatre',
  'Acting',
  'Writing',
  'Poetry',
  'Creative Writing',
  // Sports & Fitness
  'Sports',
  'Basketball',
  'Football',
  'Soccer',
  'Baseball',
  'Tennis',
  'Volleyball',
  'Swimming',
  'Running',
  'Cycling',
  'Yoga',
  'Fitness',
  'Weightlifting',
  'Martial Arts',
  'Rock Climbing',
  'Hiking',
  'Surfing',
  'Skateboarding',
  // Entertainment & Media
  'Movies',
  'TV Shows',
  'Anime',
  'Manga',
  'Comics',
  'Reading',
  'Books',
  'Podcasts',
  'Streaming',
  'Content Creation',
  'YouTube',
  'TikTok',
  'Social Media',
  // Food & Cooking
  'Food',
  'Cooking',
  'Baking',
  'Coffee',
  'Tea',
  'Craft Beer',
  'Wine',
  'Food Photography',
  // Travel & Adventure
  'Travel',
  'Backpacking',
  'Camping',
  'Road Trips',
  'International Travel',
  'Adventure Sports',
  // Academic & Intellectual
  'Research',
  'Mathematics',
  'Science',
  'Physics',
  'Chemistry',
  'Biology',
  'Astronomy',
  'History',
  'Philosophy',
  'Psychology',
  'Languages',
  'Learning Languages',
  // Social & Community
  'Volunteering',
  'Community Service',
  'Activism',
  'Politics',
  'Debate',
  'Public Speaking',
  'Networking',
  'Mentoring',
  // Hobbies & Crafts
  'Knitting',
  'Crocheting',
  'Sewing',
  'Woodworking',
  '3D Printing',
  'Model Building',
  'Collecting',
  'Board Games',
  'Card Games',
  'Puzzles',
  'Chess',
  'Magic Tricks',
  // Nature & Outdoors
  'Gardening',
  'Plants',
  'Bird Watching',
  'Nature Photography',
  'Fishing',
  'Hunting',
  'Stargazing',
  // Business & Entrepreneurship
  'Entrepreneurship',
  'Business',
  'Finance',
  'Investing',
  'Stock Trading',
  'Real Estate',
  'Marketing',
  'Sales',
  // Fashion & Style
  'Fashion',
  'Style',
  'Makeup',
  'Skincare',
  'Hair Styling',
  'Tattoos',
  'Piercings',
  // Cars & Vehicles
  'Cars',
  'Motorcycles',
  'Auto Racing',
  'Car Modifications',
  // Pets & Animals
  'Dogs',
  'Cats',
  'Pets',
  'Animal Welfare',
  // Health & Wellness
  'Meditation',
  'Mindfulness',
  'Mental Health',
  'Nutrition',
  'Wellness',
  'Self Care',
  // Other
  'Fashion Design',
  'Interior Design',
  'Architecture',
  'Engineering Projects',
  'DIY Projects',
  'Home Improvement',
];
