import { StyleSheet } from 'react-native';
import Colors, { INK, palette } from '@/constants/colors';

const homeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.light.feedBackground,
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: Colors.light.textSecondary,
    },
    categoryBar: {
        flexGrow: 0,
        flexShrink: 0,
        zIndex: 2,
        backgroundColor: Colors.light.feedBackground,
        borderBottomWidth: 3,
        borderBottomColor: INK,
    },
    feedContent: {
        flex: 1,
    },
    categoryBarContent: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 8,
    },
    categoryChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: INK,
        backgroundColor: Colors.light.card,
    },
    categoryChipActive: {
        backgroundColor: palette.orange,
    },
    categoryChipText: {
        fontSize: 13,
        fontWeight: '800' as const,
        color: INK,
    },
    categoryChipTextActive: {
        color: '#FFFFFF',
    },
    listContent: {
        padding: 16,
        paddingBottom: 100,
        gap: 16,
    },
    postCardWrap: {
        position: 'relative',
    },
    postCard: {
        backgroundColor: Colors.light.card,
        borderRadius: 24,
        borderWidth: 3,
        borderColor: INK,
        padding: 16,
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    avatarWrap: {
        marginRight: 12,
    },
    postHeaderText: {
        flex: 1,
    },
    userName: {
        fontSize: 16,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },
    timeAgo: {
        fontSize: 12,
        fontWeight: '600' as const,
        color: Colors.light.textSecondary,
        marginTop: 2,
    },
    postContent: {
        fontSize: 15,
        fontWeight: '600' as const,
        color: Colors.light.text,
        lineHeight: 22,
        marginBottom: 12,
    },
    postImage: {
        width: '100%',
        height: 250,
        borderRadius: 16,
        borderWidth: 2.5,
        borderColor: INK,
        marginBottom: 12,
        backgroundColor: Colors.light.backgroundSecondary,
    },
    postActions: {
        flexDirection: 'row',
        gap: 16,
        paddingTop: 12,
        borderTopWidth: 2.5,
        borderTopColor: INK,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    actionText: {
        fontSize: 14,
        color: Colors.light.textSecondary,
        fontWeight: '800' as const,
    },
    actionTextActive: {
        color: Colors.light.error,
    },
    commentsSection: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 2.5,
        borderTopColor: INK,
        gap: 12,
    },
    comment: {
        flexDirection: 'row',
        gap: 8,
        position: 'relative',
    },
    commentContent: {
        flex: 1,
        backgroundColor: Colors.light.card,
        borderWidth: 2,
        borderColor: INK,
        borderRadius: 14,
        padding: 10,
    },
    commentUserName: {
        fontSize: 14,
        fontWeight: '900' as const,
        color: Colors.light.text,
        marginBottom: 4,
    },
    commentText: {
        fontSize: 14,
        fontWeight: '500' as const,
        color: Colors.light.text,
        lineHeight: 20,
    },
    commentActionsRow: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 6,
    },
    commentAction: {
        paddingVertical: 4,
    },
    commentActionText: {
        fontSize: 13,
        color: Colors.light.textSecondary,
        fontWeight: '800' as const,
    },
    repliesContainer: {
        marginTop: 8,
        gap: 8,
    },
    replyRow: {
        flexDirection: 'row',
        gap: 8,
        alignItems: 'flex-start',
    },
    replyContent: {
        flex: 1,
        backgroundColor: Colors.light.background,
        borderWidth: 1.5,
        borderColor: INK,
        borderRadius: 12,
        padding: 10,
    },
    replyAuthor: {
        fontSize: 13,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },
    replyText: {
        fontSize: 13,
        fontWeight: '500' as const,
        color: Colors.light.text,
        marginTop: 2,
    },
    replyInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 8,
    },
    replyInput: {
        flex: 1,
        backgroundColor: Colors.light.card,
        borderWidth: 2,
        borderColor: INK,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        color: Colors.light.text,
        fontWeight: '600' as const,
        fontSize: 13,
    },
    replySend: {
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: palette.blue,
        borderWidth: 2,
        borderColor: INK,
        borderRadius: 10,
    },
    replySendText: {
        color: '#fff',
        fontWeight: '900' as const,
        fontSize: 13,
    },
    addComment: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    commentInput: {
        flex: 1,
        backgroundColor: Colors.light.card,
        borderWidth: 2,
        borderColor: INK,
        borderRadius: 18,
        paddingHorizontal: 16,
        paddingVertical: 8,
        fontSize: 14,
        fontWeight: '600' as const,
        color: Colors.light.text,
    },
    commentSubmit: {
        fontSize: 14,
        fontWeight: '900' as const,
        color: Colors.light.primary,
    },
    commentSubmitDisabled: {
        color: Colors.light.placeholder,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(22, 13, 40, 0.55)',
    },
    modalContent: {
        backgroundColor: Colors.light.card,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        borderTopWidth: 3,
        borderColor: INK,
        padding: 24,
        minHeight: 300,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },
    modalClose: {
        fontSize: 16,
        fontWeight: '800' as const,
        color: Colors.light.textSecondary,
    },
    postInput: {
        backgroundColor: Colors.light.card,
        borderWidth: 2.5,
        borderColor: INK,
        borderRadius: 18,
        padding: 16,
        fontSize: 16,
        fontWeight: '600' as const,
        color: Colors.light.text,
        minHeight: 120,
        textAlignVertical: 'top',
        marginBottom: 16,
    },
    fieldLabel: {
        fontSize: 13,
        fontWeight: '800' as const,
        color: Colors.light.text,
        marginBottom: 8,
    },
    chipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 12,
    },
    extraInput: {
        backgroundColor: Colors.light.card,
        borderWidth: 2,
        borderColor: INK,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 14,
        fontWeight: '600' as const,
        color: Colors.light.text,
        marginBottom: 12,
    },
    pollOptionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    pollOptionInput: {
        flex: 1,
    },
    pollOptionRemove: {
        padding: 8,
        marginBottom: 12,
    },
    addOptionButton: {
        alignSelf: 'flex-start',
        marginBottom: 12,
    },
    addOptionText: {
        fontSize: 13,
        fontWeight: '800' as const,
        color: Colors.light.primary,
    },
    wishboneRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
        marginBottom: 12,
        borderWidth: 2.5,
        borderColor: INK,
        borderRadius: 16,
        overflow: 'hidden',
        height: 160,
    },
    wishboneSlot: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.light.backgroundSecondary,
    },
    wishboneImage: {
        width: '100%',
        height: '100%',
    },
    wishboneDivider: {
        width: 3,
        backgroundColor: INK,
    },
    tagInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    tagInput: {
        flex: 1,
    },
    addTagButton: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: INK,
        backgroundColor: palette.skyBlue,
        marginBottom: 12,
    },
    addTagButtonText: {
        fontSize: 13,
        fontWeight: '900' as const,
        color: INK,
    },
    modalActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    imageButton: {
        padding: 10,
        backgroundColor: Colors.light.backgroundSecondary,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: INK,
    },
    postButtonWrap: {
        position: 'relative',
    },
    postButton: {
        backgroundColor: palette.blue,
        borderRadius: 18,
        borderWidth: 2.5,
        borderColor: INK,
        paddingVertical: 14,
        paddingHorizontal: 32,
        alignItems: 'center',
        minWidth: 100,
    },
    postButtonDisabled: {
        backgroundColor: '#C7C2D6',
    },
    postButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '900' as const,
    },
    selectedImageContainer: {
        position: 'relative',
        marginBottom: 16,
        borderRadius: 12,
        overflow: 'hidden',
    },
    selectedImage: {
        width: '100%',
        height: 200,
        borderRadius: 12,
    },
    removeImageButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(22,13,40,0.6)',
        borderRadius: 12,
        padding: 4,
    },
    profileModalContainer: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    profileModalHeader: {
        paddingTop: 48,
        paddingHorizontal: 16,
        paddingBottom: 12,
        backgroundColor: palette.navy,
        borderBottomWidth: 3,
        borderBottomColor: INK,
    },
    modalCloseText: {
        color: '#FFFFFF',
        fontWeight: '900' as const,
        fontSize: 16,
    },
    profileModalLoading: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileModalContent: {
        padding: 20,
        gap: 16,
    },
    profileHeader: {
        alignItems: 'center',
        gap: 8,
    },
    profileName: {
        fontSize: 24,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },
    profileMajor: {
        fontSize: 15,
        fontWeight: '600' as const,
        color: Colors.light.textSecondary,
    },
    profileActions: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 10,
    },
    profileButtonWrap: {
        position: 'relative',
    },
    profileButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 14,
        borderWidth: 2.5,
        borderColor: INK,
    },
    profilePrimary: {
        backgroundColor: palette.blue,
    },
    profileButtonDisabled: {
        backgroundColor: '#D8D3E0',
    },
    profileSecondary: {
        backgroundColor: Colors.light.card,
    },
    profileButtonText: {
        color: '#fff',
        fontWeight: '900' as const,
    },
    profileSecondaryText: {
        color: Colors.light.text,
    },
    profileSection: {
        gap: 8,
    },
    profileSectionTitle: {
        fontSize: 15,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },
    profileBody: {
        fontSize: 15,
        fontWeight: '500' as const,
        color: Colors.light.text,
        lineHeight: 22,
    },
    profileChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    reportButton: {
        backgroundColor: Colors.light.error,
        alignSelf: 'center',
        marginTop: 8,
        paddingHorizontal: 18,
    },
    reportText: {
        color: '#fff',
    },
    moreButton: {
        padding: 6,
    },
    commentOptions: {
        position: 'absolute',
        top: 8,
        right: 8,
        padding: 4,
    },
    optionsOverlay: {
        flex: 1,
        backgroundColor: 'rgba(22,13,40,0.5)',
        justifyContent: 'flex-end',
    },
    optionsCard: {
        backgroundColor: Colors.light.card,
        padding: 16,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        borderTopWidth: 3,
        borderColor: INK,
        gap: 8,
    },
    optionsItem: {
        paddingVertical: 12,
    },
    createOptionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 12,
    },
    optionsItemText: {
        fontSize: 16,
        color: Colors.light.text,
        fontWeight: '700' as const,
    },
    optionsItemDestructive: {
        fontSize: 16,
        color: Colors.light.error,
        fontWeight: '900' as const,
    },
    optionsCancel: {
        paddingVertical: 12,
    },
    optionsCancelText: {
        fontSize: 16,
        color: Colors.light.textSecondary,
        fontWeight: '700' as const,
        textAlign: 'center',
    },
    editModalContent: {
        backgroundColor: Colors.light.card,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        borderTopWidth: 3,
        borderColor: INK,
        padding: 24,
    },
    editModalActions: {
        marginTop: 8,
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
    },
    sectionIconWell: {
        width: 28,
        height: 28,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: INK,
        backgroundColor: palette.amber,
        alignItems: 'center',
        justifyContent: 'center',
    },
    section: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 15,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },
    infoCardWrap: {
        position: 'relative',
    },
    infoCard: {
        backgroundColor: Colors.light.card,
        borderRadius: 20,
        borderWidth: 3,
        borderColor: INK,
        padding: 16,
        gap: 14,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    infoIcon: {
        width: 36,
        height: 36,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: INK,
        backgroundColor: palette.skyBlue,
        justifyContent: 'center',
        alignItems: 'center',
    },
    infoContent: {
        flex: 1,
    },
    infoLabel: {
        fontSize: 12,
        color: Colors.light.textSecondary,
        fontWeight: '800' as const,
        letterSpacing: 0.3,
    },
    infoValue: {
        fontSize: 15,
        color: Colors.light.text,
        fontWeight: '800' as const,
        marginTop: 1,
    },

    //   For Stats Section (not used yet)
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: Colors.light.card,
        borderRadius: 16,
        borderWidth: 2.5,
        borderColor: INK,
        marginTop: 8,
        gap: 12,
    },

    statCard: {
        flex: 1,
        backgroundColor: Colors.light.backgroundSecondary,
        paddingVertical: 14,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: INK,
        alignItems: 'center',
        justifyContent: 'center',
    },

    statNumber: {
        fontSize: 22,
        fontWeight: '900' as const,
        color: Colors.light.text,
    },

    statLabel: {
        fontSize: 13,
        color: Colors.light.textSecondary,
        marginTop: 4,
        fontWeight: '700' as const,
    },


});

export default homeStyles;
