// app/(tabs)/profile.styles.ts
import { StyleSheet } from 'react-native'
import Colors, { INK, palette } from '@/constants/colors'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.feedBackground,
  },
  logoutButton: {
    paddingHorizontal: 16,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  header: {
    alignItems: 'center',
    paddingTop: 32,
    paddingBottom: 20,
    backgroundColor: palette.skyBlue,
    borderBottomWidth: 3,
    borderBottomColor: INK,
  },
  avatarContainer: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 16,
  },
  // For profile picture edit button
  editProfileIconButton: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: palette.orange,
    borderRadius: 18,
    borderWidth: 2.5,
    borderColor: INK,
    padding: 7,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  name: {
    fontSize: 26,
    fontWeight: '900' as const,
    color: Colors.light.text,
    marginBottom: 4,
  },
  majorAndYearContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 8,
  },
  major: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: Colors.light.textSecondary,
  },
  pointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: palette.amber,
    borderWidth: 2,
    borderColor: INK,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 8,
  },
  pointsBadgeText: {
    fontSize: 13,
    fontWeight: '900' as const,
    color: INK,
  },
  bioSection: {
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 2,
  },
  bioText: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: Colors.light.text,
    textAlign: 'center',
    marginBottom: 4,
  },
  addBioSection: {
    padding: 16,
    backgroundColor: Colors.light.card,
    borderWidth: 2,
    borderColor: INK,
    borderRadius: 16,
    marginVertical: 8,
  },
  bioInput: {
    backgroundColor: Colors.light.card,
    borderWidth: 2,
    borderColor: INK,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    fontWeight: '600' as const,
    color: Colors.light.text,
    marginBottom: 12,
  },
  charCount: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.light.textSecondary,
    textAlign: 'right',
    marginBottom: 8,
  },
  statsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 12, //spacing between Posts, Connections, and Likes
  },
  section: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  sectionIconWell: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: INK,
    backgroundColor: palette.amber,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '900' as const,
    color: Colors.light.text,
  },
  interestsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoCardWrap: {
    position: 'relative',
  },
  infoCard: {
    backgroundColor: Colors.light.card,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: INK,
    padding: 16,
    gap: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  infoIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: INK,
    backgroundColor: palette.skyBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: Colors.light.textSecondary,
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 15,
    color: Colors.light.text,
    fontWeight: '800' as const,
  },
  joinedSection: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  joinedText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.light.textSecondary,
  },
  editBioBadge: {
    backgroundColor: palette.blue,
    borderWidth: 2,
    borderColor: INK,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    marginTop: 6,
    alignSelf: 'center',
  },
  editBioText: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: '#ffffff',
    textAlign: 'center',
  },
  saveBioBadge: {
    backgroundColor: palette.blue,
    borderWidth: 2,
    borderColor: INK,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    marginTop: 6,
    alignSelf: 'center',
  },
  saveBioText: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: '#ffffff',
    textAlign: 'center',
  },
  addBioBadge: {
    backgroundColor: palette.blue,
    borderWidth: 2,
    borderColor: INK,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    marginTop: 6,
    alignSelf: 'center',
  },
  addBioText: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: '#ffffff',
    textAlign: 'center',
  },
uploadOverlay: {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  zIndex: 999,
  justifyContent: "center",
  alignItems: "center",
  backgroundColor: "rgba(22,13,40,0.4)",
},

uploadingText: {
  marginTop: 16,
  color: "#fff",
  fontSize: 16,
  fontWeight: "700" as const,
},
editButton: {
  paddingHorizontal: 8,
},
editContainer: {
  flex: 1,
  backgroundColor: Colors.light.background,
},
editHeader: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingHorizontal: 16,
  paddingTop: 48,
  paddingBottom: 12,
  backgroundColor: palette.navy,
  borderBottomWidth: 3,
  borderBottomColor: INK,
},
cancelText: {
  color: '#FFFFFF',
  fontWeight: '700' as const,
},
editTitle: {
  fontSize: 18,
  fontWeight: '900' as const,
  color: '#FFFFFF',
},
saveButton: {
  padding: 6,
},
editContent: {
  padding: 20,
  gap: 16,
},
editAvatarWrap: {
  alignSelf: 'center',
  position: 'relative',
},
editAvatarOverlay: {
  position: 'absolute',
  bottom: 2,
  right: 2,
  backgroundColor: palette.orange,
  borderWidth: 2,
  borderColor: INK,
  borderRadius: 14,
  paddingHorizontal: 10,
  paddingVertical: 6,
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
},
editAvatarText: {
  color: '#fff',
  fontWeight: '800' as const,
  fontSize: 12,
},
editField: {
  gap: 6,
},
editLabel: {
  fontSize: 14,
  fontWeight: '800' as const,
  color: Colors.light.text,
},
editInput: {
  backgroundColor: Colors.light.card,
  borderWidth: 2,
  borderColor: INK,
  borderRadius: 12,
  paddingHorizontal: 14,
  paddingVertical: 10,
  fontSize: 15,
  fontWeight: '600' as const,
  color: Colors.light.text,
},
editTextarea: {
  minHeight: 100,
  textAlignVertical: 'top',
},
interestsEditScrollView: {
  maxHeight: 300,
},
interestsEditContainer: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  gap: 10,
  paddingBottom: 8,
},
interestChipEdit: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 6,
  paddingHorizontal: 14,
  paddingVertical: 8,
  borderRadius: 16,
  backgroundColor: Colors.light.card,
  borderWidth: 2,
  borderColor: INK,
},
interestChipEditSelected: {
  backgroundColor: palette.blue,
},
interestChipTextEdit: {
  fontSize: 13,
  fontWeight: '800' as const,
  color: Colors.light.text,
},
interestChipTextEditSelected: {
  color: '#ffffff',
},
chipIconEdit: {
  marginLeft: 2,
},
friendsModalContainer: {
  flex: 1,
  backgroundColor: Colors.light.background,
},
friendsModalHeader: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingHorizontal: 16,
  paddingTop: 20,
  paddingBottom: 16,
  backgroundColor: palette.navy,
  borderBottomWidth: 3,
  borderBottomColor: INK,
},
friendsModalTitle: {
  fontSize: 18,
  fontWeight: '900' as const,
  color: '#FFFFFF',
},
friendsModalClose: {
  fontSize: 15,
  fontWeight: '800' as const,
  color: '#FFFFFF',
},
friendsModalEmpty: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
},
friendsModalEmptyText: {
  fontSize: 15,
  fontWeight: '600' as const,
  color: Colors.light.textSecondary,
},
friendsModalList: {
  padding: 16,
  gap: 10,
},

})

export default styles
